package com.cg.empm.model;

public enum EventManagementAppMenu {
	ADD,REMOVE,LIST,LISTOFASCENDINGORDEROFDATESHEDULED,LISTOFALPHABETICALORDEROFLOCATION,LISTOFPARTICULARLOCATION,LISTOFPARTICULARDATESHEDULED,QUIT;

}
